### PR TITLE
Add mapbox cluster features click support

### PR DESCRIPTION
**Pull request by edellucien**
# How to

Use asynchronous method 'getClusterLeaves' from mapbox to retrieve features in a cluster on click:
https://docs.mapbox.com/mapbox-gl-js/api/sources/#geojsonsource#getclusterleaves

# Others

- [x] It's not a hack or at least an unauthorized hack :).
- [ ] The images added are optimized.
- [x] Everything in ticket description has been fixed.
- [x] The author of the MR has made its own review before assigning the reviewer.
- [x] The title means something for a human being.
- [ ] The title contains [WIP] if it's necessary.
- [ ] Labels applied. if it's a release? a hotfix?
- [ ] The new class' members & methods are well documented
- [ ] Tests added.

### CODE REVIEW

**Comment by mhaertwig** [comment]
@edellucien @friedjoff We need this functionality for `trafimage-maps` topic (construction). Should we keep this functionality in `mobility-toolbox-js` or move it to a layer in `trafimage-maps` extending the `MapboxLayer`?

**Comment by friedjoff** [comment]
This looks rather specific to me and better suited for a special `MapboxClusterLayer` class, maybe for now directly in `trafiamge-maps`. At least we should document this behavior.

**Comment by edellucien** [comment]
Friedjoff added this changes directly in wkp: https://github.com/geops/trafimage-maps/pull/799
We keep this MR open until the changes are resolved in wkp.

**Comment by oterral** [comment]
Trafimage PR is merged so we can close this. Reopen if not

**Pull request closed without merging**
